project:
  type: website

website:
  title: "Ananya Pujary"
  site-url: https://github.com/apujary
  twitter-card:
    creator: ""
    site: ""
  favicon: images/DACSS_Round_Network.png
  navbar:
    background: "#881c1c"
    logo: images/UMass White Wordmark Horiz.png
    right:
      - text: "Resume"
        file: AnanyaPujary_Resume copy.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/ananya-pujary/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/apujary
        aria-label: GitHub

execution:
  freeze: auto


format:
  html:
    mainfont: Open Sans
    linkcolor: "#881c1c"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
